{% set name = "evalica" %}
{% set version = "0.4.0.post1" %}
{% set sha256 = "4ec1e857ffde448e582794e06d3336a46e93aa3fe64aec8ebbc7eadb53a66807" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evalica-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  ignore_run_exports:
    - python
    - libgfortran5
  entry_points:
    - evalica = evalica.__main__:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"  # [unix]
    - set "PKG_CONFIG_PATH=%PREFIX%\Library\lib\pkgconfig"  # [win]
    - MATURIN_PEP517_ARGS="--features python,openblas-src" {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [unix]
    - set "MATURIN_PEP517_ARGS=--features python,openblas-src" && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [win]
  python_version_independent: true  # [is_abi3]
  skip: true  # [is_abi3 and not is_python_min]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openblas
    - maturin
    - pip
    - python-abi3  # [is_abi3]
    - python
  run:
    - python
    - pandas
    - scipy
    - libopenblas

test:
  imports:
    - evalica
  commands:
    - pip check
    - evalica --help
    - {{ PYTHON }} -c 'import evalica, sys; print("BLAS:", blas := evalica._brzo.HAS_BLAS); sys.exit(int(not blas))'
    - abi3audit $SP_DIR/evalica/_brzo.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}  # [unix and is_abi3]
    - abi3audit %SP_DIR%\evalica\_brzo.pyd -s -v --assume-minimum-abi3 {{ python_min }}  # [win and is_abi3]
  requires:
    - pip
    - abi3audit  # [is_abi3]

about:
  home: https://github.com/dustalov/evalica
  summary: Evalica, your favourite evaluation toolkit.
  description: |
    Evalica is an evaluation toolkit for statistical analysis,
    combining fast Rust implementations with Python APIs for
    ranking, reliability, and uncertainty estimation.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dustalov
