{% set name = "evalica" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evalica-{{ version }}.tar.gz
  sha256: a75ceb91e7dc739bc73ccb3bcf2b773b21850506c898cca71caa55f26bef8345

build:
  entry_points:
    - evalica = evalica.__main__:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - maturin
    - numpy
    - pandas
    - pip
    - python
  run:
    - pandas
    - python

test:
  imports:
    - evalica
  commands:
    - pip check
    - evalica --help
  requires:
    - pip

about:
  home: https://github.com/dustalov/evalica
  summary: Evalica, your favourite evaluation toolkit.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dustalov
