{% set name = "evalica" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evalica-{{ version }}.tar.gz
  sha256: 44de2a2c4b742ca4a82c9fa032dec0ce6167e78e159a8c07dbb4268cf7e857b5

build:
  entry_points:
    - evalica = evalica.__main__:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - maturin
    - numpy
    - pandas
    - pip
    - python
  run:
    - pandas
    - python

test:
  imports:
    - evalica
  commands:
    - pip check
    - evalica --help
  requires:
    - pip

about:
  home: https://github.com/dustalov/evalica
  summary: Evalica, your favourite evaluation toolkit.
  description: |
    Evalica is a Python library that transforms pairwise comparisons
    into ranked lists of items. It offers convenient high-performant
    Rust implementations of the corresponding methods via PyO3,
    and additionally provides naïve Python code for most of them.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dustalov
