{% set name = "evalica" %}
{% set version = "0.4.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evalica-{{ version }}.tar.gz
  sha256: 4ec1e857ffde448e582794e06d3336a46e93aa3fe64aec8ebbc7eadb53a66807

build:
  number: 0
  entry_points:
    - evalica = evalica.__main__:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"  # [not win]
    - MATURIN_PEP517_ARGS="--features python,openblas-src" {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [not win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [win]
  python_version_independent: true  # [is_abi3]
  skip: true  # [is_abi3 and not is_python_min]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config  # [not win]
  host:
    - libblas * *openblas
    - openblas  # [not win]
    - maturin
    - numpy
    - pandas
    - pip
    - python
  run:
    - pandas
    - python
    - scipy

test:
  imports:
    - evalica
  commands:
    - pip check
    - evalica --help
    - abi3audit $SP_DIR/spam.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}  # [unix and is_abi3]
    - abi3audit %SP_DIR%/spam.pyd -s -v --assume-minimum-abi3 {{ python_min }}  # [win and is_abi3]
  requires:
    - pip
    - abi3audit  # [is_abi3]

about:
  home: https://github.com/dustalov/evalica
  summary: Evalica, your favourite evaluation toolkit.
  description: |
    Evalica is a Python library that transforms pairwise comparisons
    into ranked lists of items. It offers convenient high-performant
    Rust implementations of the corresponding methods via PyO3,
    and additionally provides naïve Python code for most of them.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dustalov
