{% set name = "evalica" %}
{% set version = "0.4.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evalica-{{ version }}.tar.gz
  sha256: 4ec1e857ffde448e582794e06d3336a46e93aa3fe64aec8ebbc7eadb53a66807

build:
  entry_points:
    - evalica = evalica.__main__:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - MATURIN_PEP517_ARGS="--features openblas-src" {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config  # [not win]
  host:
    - libblas * *openblas
    - maturin
    - numpy
    - pandas
    - pip
    - python
  run:
    - pandas
    - python

test:
  imports:
    - evalica
  commands:
    - pip check
    - evalica --help
  requires:
    - pip

about:
  home: https://github.com/dustalov/evalica
  summary: Evalica, your favourite evaluation toolkit.
  description: |
    Evalica is a Python library that transforms pairwise comparisons
    into ranked lists of items. It offers convenient high-performant
    Rust implementations of the corresponding methods via PyO3,
    and additionally provides naïve Python code for most of them.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dustalov
